package com.membership.hub.model.shared;

public enum Skills {
    QUALITYCONTROL, DIGITALMEDIA, NETWORKING, WEBANALYTICS, VIDEOCREATION, DESIGN, CODING, TESTING, MARKETING, RESEARCH, PHOTOSHOP, QATESTING, RISKMANAGEMENT,
    COMMUNICATION, PUBLICSPEAKING, WRITING, CREATIVITY, INNOVATION, LEADERSHIP, MENTORING, SELLING, TEAMWORK, PLANNING, PERSUASION
}
